'use strict';
const $=id=>document.getElementById(id);let step=0,spectGeneration=0,ctGeneration=0,spect=null,ctGroups=new Map();
function status(s){$('status').textContent=s;}
function navigate(value){step=Math.max(0,Math.min(3,value));document.querySelectorAll('.step').forEach((s,i)=>s.hidden=i!==step);document.querySelectorAll('[data-step]').forEach(b=>{b.classList.toggle('active',+b.dataset.step===step);b.setAttribute('aria-current',+b.dataset.step===step?'step':'false');});$('prev').disabled=step===0;$('next').disabled=step===3;$('position').textContent=`Paso ${step+1} de 4`;$('empty').hidden=false;document.dispatchEvent(new Event('lab95navigate'));}
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=async()=>{const target=+b.dataset.step;if(step===1&&target===2&&window.Lab95Live?.advanceFromRegistration){await Lab95Live.advanceFromRegistration();return;}navigate(target);});$('prev').onclick=()=>navigate(step-1);$('next').onclick=async()=>{if(step===1&&window.Lab95Live?.advanceFromRegistration){await Lab95Live.advanceFromRegistration();return;}navigate(step+1);};$('home').onclick=()=>navigate(0);
function clearResults(){document.dispatchEvent(new Event("lab95invalidate"));$('empty').hidden=false;$('mode').textContent='Estudio nuevo · aún sin reconstruir';}
function reset(){spectGeneration++;ctGeneration++;clearResults();spect=null;ctGroups.clear();for(const id of ['spectFile','spectFolder','ctFiles','ctFolder'])$(id).value='';$('spectInfo').textContent='No se ha cargado SPECT.';$('ctInfo').textContent='No se ha cargado TC.';$('spectSeries').replaceChildren(new Option('Sin adquisiciones',''));$('spectSeries').disabled=true;$('ctSeries').replaceChildren(new Option('Sin series',''));$('ctSeries').disabled=true;$('caseName').textContent='Sin estudio';$('caseInfo').textContent='Carga proyecciones SPECT y una serie TC.';status('Listo para un nuevo estudio.');navigate(0);}
$('new').onclick=reset;
function options(){return {educational:true,attenuationCorrection:$('ac').checked,scatter:$('scatter').checked,scatterWeight:+$('weight').value,resolutionRecovery:$('psf').checked,distanceDependent:$('psf').checked&&$('distance').checked,axialRecovery:$('psf').checked&&$('axial').checked,scatterSmoothing:$('scatter').checked&&$('scatterFilter').checked,scatterFwhm:+$('scatterFwhm').value,psfFwhm100:+$('psfFwhm100').value,psfIntrinsic:+$('psfIntrinsic').value,postFilter:$('filter').checked,postFilterFWHMmm:+$('fwhm').value,initialization:$('fbpStart').checked?'FBP':'uniform',iterations:+$('iterations').value,subsets:+$('subsets').value,status:'configuration only; not yet executed'};}
function dependencies(){$('weight').disabled=$('scatterFilter').disabled=!$('scatter').checked;$('scatterFwhm').disabled=!$('scatter').checked||!$('scatterFilter').checked;for(const id of ['distance','axial','psfFwhm100','psfIntrinsic'])$(id).disabled=!$('psf').checked;$('fwhm').disabled=!$('filter').checked;}
$('parameters').addEventListener('change',()=>{dependencies();status('Configuración modificada; pendiente de cálculo.');});
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
$('saveConfig').onclick=()=>{for(const el of $('parameters').querySelectorAll('input[type=number]'))if(!el.disabled&&!el.checkValidity()){el.reportValidity();return;}download(new Blob([JSON.stringify(options(),null,2)],{type:'application/json'}),'configuracion-spect-educativo.json');status('Configuración guardada. No se ha generado una reconstrucción.');};
$('help').onclick=()=>$('about').showModal();$('closeHelp').onclick=()=>$('about').close();
async function readHeader(file){const bytes=new Uint8Array(await file.arrayBuffer());const d=dicomParser.parseDicom(bytes,{untilTag:'x7fe00010'});return d;}
const str=(d,t)=>(d.string(t)||'').trim();
$('spectFile').onchange=async()=>{const file=$('spectFile').files[0];if(!file)return;clearResults();const epoch=++spectGeneration;spect=null;$('caseName').textContent='Estudio importado';$('caseInfo').textContent='Lectura de cabeceras; reconstrucción pendiente de integración.';status('Leyendo SPECT…');try{const d=await readHeader(file);if(epoch!==spectGeneration)return;if(str(d,'x00080060')!=='NM')throw Error('Se espera modalidad NM.');if(!str(d,'x00080008').includes('TOMO')||str(d,'x00080008').includes('RECON'))throw Error('Selecciona las proyecciones tomográficas originales, no una reconstrucción.');const nf=Number(str(d,'x00280008'));if(!Number.isInteger(nf)||nf<2)throw Error('Se necesita una adquisición tomográfica multiframe.');spect={frame:str(d,'x00200052'),frames:nf,rows:d.uint16('x00280010'),cols:d.uint16('x00280011'),windows:d.uint16('x00540011')||1};$('spectInfo').textContent=`${file.name} · ${spect.rows} × ${spect.cols} · ${nf} imágenes · ${spect.windows} ventana(s). Cabecera NM reconocida; geometría y píxeles pendientes de validación por el motor.`;ctMessage();status('Cabecera SPECT leída. No se ha reconstruido este estudio.');}catch(e){$('spectInfo').textContent='No cargado: '+e.message;status('Revisa el archivo SPECT.');}};
async function loadCT(files){if(!files.length)return;clearResults();const epoch=++ctGeneration;ctGroups.clear();$('ctSeries').disabled=true;$('ctSeries').replaceChildren();let ignored=0;try{for(let i=0;i<files.length;i++){if(epoch!==ctGeneration)return;try{const d=await readHeader(files[i]);if(epoch!==ctGeneration)return;if(str(d,'x00080060')!=='CT')throw Error();const key=str(d,'x0020000e'),frame=str(d,'x00200052');if(!key||!str(d,'x00200032'))throw Error();if(!ctGroups.has(key))ctGroups.set(key,{count:0,frame,name:str(d,'x0008103e')||'Serie TC'});ctGroups.get(key).count++;}catch(e){ignored++;}if(i%20===0){status(`Leyendo cabeceras TC: ${i+1}/${files.length}`);await new Promise(r=>setTimeout(r,0));}}if(!ctGroups.size)throw Error('No se encontraron cortes TC con posición y serie.');for(const [key,g]of [...ctGroups].sort((a,b)=>b[1].count-a[1].count))$('ctSeries').add(new Option(`${g.name} · ${g.count} archivos`,key));$('ctSeries').disabled=false;ctMessage();status(`Lectura TC terminada. ${ignored} archivo(s) omitidos. Mapa μ aún pendiente de cálculo.`);}catch(e){$('ctInfo').textContent=e.message;status('No se ha cargado una serie TC.');}}
function ctMessage(){const g=ctGroups.get($('ctSeries').value);if(!g)return;$('ctInfo').textContent=`${g.count} archivos TC reconocidos. `+(spect?(g.frame&&spect.frame&&g.frame===spect.frame?'Mismo marco espacial que el SPECT; requiere revisar el registro.':'Marco espacial distinto o ausente: no se combinarán automáticamente.'):'Carga SPECT para comprobar el marco espacial.')+' Mapa de atenuación aún no calculado.';}
$('ctFiles').onchange=()=>loadCT([...$('ctFiles').files]);$('ctFolder').onchange=()=>loadCT([...$('ctFolder').files]);$('ctSeries').onchange=ctMessage;dependencies();navigate(0);
