'use strict';
const SPECT95_LESSONS={
 overview:{title:'De las proyecciones a la imagen',comparison:'iterations',sections:[
 ['¿Qué estamos intentando ver?','El SPECT registra señales desde distintos ángulos. Cada vista superpone la actividad que encuentra en su recorrido; todavía no es un corte del cuerpo. Reconstruir consiste en combinar esas vistas para estimar dónde se encontraba la actividad. En el fantoma conocemos la respuesta: los discos brillantes representan mayor captación y el disco oscuro, menor captación.'],
 ['Dos maneras de formar la imagen','FBP obtiene rápidamente una primera imagen útil para reconocer formas y revisar la alineación con el TC. OSEM parte de una imagen provisional, calcula cómo se vería desde los detectores y la va corrigiendo para explicar mejor las señales registradas. Las opciones activadas determinan qué efectos físicos tiene en cuenta.'],
 ['Cómo leer las comparaciones','Busca el foco pequeño, el borde del objeto y la zona fría. Una imagen más lisa puede ocultar detalles; una más contrastada puede tener más ruido. Los ejemplos siguientes ya están calculados y no cambian las opciones de tu estudio.'] ]},
 ac:{title:'Atenuación: la señal que no llega',comparison:'ac',sections:[
 ['La idea','Parte de los fotones se pierde al atravesar el cuerpo. Por eso una región puede parecer menos activa aunque realmente no lo sea. La corrección de atenuación ayuda a OSEM a distinguir entre poca actividad y señal perdida durante el recorrido. No consiste en iluminar por igual toda la imagen.'],
 ['Para qué sirve el TC','El TC aporta una descripción de los tejidos que la señal debe atravesar. El simulador la transforma en un mapa aproximado de atenuación. El registro coloca ese mapa en la misma posición que el SPECT: si se desplaza, la corrección puede aplicarse al lugar equivocado. Suponer aire donde falta TC tampoco recupera la anatomía ausente.'],
 ['Qué observar','En el ejemplo, las reconstrucciones parten de las mismas señales atenuadas y usan la misma escala. Al activar la corrección con el mapa conocido, se recupera parte de la intensidad perdida. En un paciente, el resultado depende además del registro y de la calidad del mapa.'] ]},
 scatter:{title:'Dispersión: señal que llega desde una dirección engañosa',comparison:'scatter',sections:[
 ['La idea','Un fotón puede cambiar de dirección dentro del cuerpo y aun así llegar al detector. Si se interpreta como si hubiera viajado directamente, aporta señal en lugares que no corresponden a su origen. Esto tiende a reducir el contraste y a rellenar zonas de baja captación.'],
 ['Qué hacen las opciones','La ventana energética inferior ofrece una pista sobre la dispersión. El peso controla cuánto confiamos en esa contribución estimada; no expresa qué porcentaje de la imagen es dispersión. El suavizado de esa ventana reduce sus fluctuaciones antes de usarla. Es distinto del suavizado final de la reconstrucción.'],
 ['Qué observar','En el fantoma, la zona fría se distingue mejor cuando se tiene en cuenta el fondo dispersado. Aquí conocemos ese fondo exactamente. En el estudio real solo lo estimamos: aumentarlo demasiado puede eliminar señal que sí pertenece al objeto, y aumentarlo poco deja dispersión sin compensar.'] ]},
 psf:{title:'Respuesta del colimador: por qué un punto parece una mancha',comparison:'psf',sections:[
 ['La idea','El colimador y el detector no representan un punto como un punto perfecto. Su señal ocupa una pequeña región. Dos estructuras cercanas pueden mezclarse, y un foco pequeño puede parecer más grande y menos intenso. Recuperar resolución consiste en incluir ese desenfoque en el proceso de reconstrucción.'],
 ['Distancia y anchura','En general, una fuente más alejada del colimador se ve más borrosa. La opción de distancia permite representar esa variación. La anchura a 100 mm describe el tamaño de la mancha a una distancia de referencia; la resolución intrínseca representa la contribución del detector. En este simulador son ajustes educativos, no una medición del equipo.'],
 ['Qué observar','Compara la separación de los focos y sus bordes. El modelo puede recuperar contraste, pero no crea información ilimitada: también puede realzar ruido o formar contornos artificiales. Un borde muy intenso no demuestra por sí solo una reconstrucción más fiel.'] ]},
 axial:{title:'Recuperar detalle también entre cortes',comparison:'axial',sections:[
 ['La idea','El desenfoque puede extenderse hacia los cortes vecinos, además de hacerlo dentro de cada corte. Una estructura corta puede parecer alargada al verla en coronal o sagital. La opción axial incluye esa mezcla entre planos.'],
 ['Por qué tarda más','Al activarla, un corte ya no puede resolverse por completo de manera independiente: necesita la información de sus vecinos. El volumen se procesa conjuntamente y aumenta el trabajo. La diferencia suele ser más fácil de reconocer en vistas coronal y sagital que mirando solo un axial.'],
 ['Qué muestra el ejemplo','La comparación siguiente aísla el efecto de la mezcla entre cortes mediante un fantoma tridimensional. Observa los extremos superior e inferior. Es una demostración de recuperación de desenfoque, no una validación de la reconstrucción SPECT del paciente.'] ]},
 iterations:{title:'Iteraciones: refinar una estimación',comparison:'iterations',sections:[
 ['La idea','OSEM comprueba repetidamente si la imagen provisional explica las señales medidas. Una iteración recorre todos los grupos de vistas. Al principio se reconocen las formas generales; con más actualizaciones pueden recuperarse diferencias de captación y detalles.'],
 ['Por qué más no siempre se ve mejor','Los datos también contienen fluctuaciones aleatorias. Al insistir en reproducirlos, la imagen puede adquirir textura y puntos brillantes. El suavizado puede moderar esa textura, pero no convierte automáticamente un resultado en más exacto.'],
 ['Cómo interpretar el progreso','Compara simultáneamente los focos, el fondo y los contornos. El primer resultado del simulador utiliza una iteración y un subconjunto. Los posteriores conservan sus propios parámetros en el historial, para que sepas qué produjo cada imagen.'] ]},
 subsets:{title:'Subconjuntos: actualizar por grupos de vistas',comparison:'subsets',sections:[
 ['La idea','En lugar de esperar a revisar todas las vistas, OSEM puede corregir la imagen después de examinar cada grupo de ángulos. Así la imagen cambia varias veces durante una misma iteración. Los grupos se distribuyen alrededor del objeto para aportar direcciones variadas.'],
 ['Qué cambia al aumentarlos','Con más grupos, a menudo se ve una evolución más rápida durante las primeras iteraciones. Sin embargo, cada actualización utiliza menos vistas y puede producir un comportamiento diferente. No basta con comparar el número de iteraciones sin mirar también los subconjuntos.'],
 ['Comparación realizada','Aquí se mantienen los datos y cuatro iteraciones, y solo cambia el número de grupos. Esto muestra el efecto de esa opción, no una comparación a igual tiempo de cálculo. La duración real depende también de las correcciones y del equipo.'] ]},
 initialization:{title:'Inicio uniforme o desde FBP',comparison:'initialization',sections:[
 ['La idea','Antes de la primera actualización hay que proporcionar una imagen inicial. El inicio uniforme distribuye la actividad sin dar preferencia a una estructura. El inicio desde FBP aporta desde el comienzo las formas que esa reconstrucción ya ha encontrado.'],
 ['Ventajas y límites','Partir de FBP puede hacer que las estructuras aparezcan antes, pero también arrastra parte de su ruido y sus artefactos. No significa que OSEM sea simplemente un filtro de FBP: sigue comparando sus predicciones con las proyecciones originales.'],
 ['En este simulador','Esta opción utiliza la FBP original preparada para ser un punto de partida válido, no la copia suavizada que se muestra para facilitar el registro. El fantoma compara ambos inicios con exactamente una iteración y un grupo. No permite deducir el flujo interno de Siemens.'] ]},
 gaussian:{title:'Suavizado: menos textura, menos detalle',comparison:'gaussian',sections:[
 ['La idea','Suavizar mezcla la intensidad de cada punto con la de sus vecinos. Las pequeñas fluctuaciones se hacen menos visibles y las regiones se ven más homogéneas. Al mismo tiempo, los bordes se difuminan y los focos pequeños pueden perder contraste.'],
 ['Qué significa la anchura','La FWHM expresa el alcance del suavizado en milímetros. Un valor mayor mezcla información de una zona más extensa. No necesitas calcular una fórmula para interpretarlo: piensa en cuánto se extiende una pequeña mancha antes de distinguirla de su entorno.'],
 ['Tres lugares distintos','El suavizado para registro facilita comparar los contornos de la FBP y el TC. El de dispersión estabiliza la señal que estima fotones dispersados. El final cambia el aspecto del resultado OSEM. Aunque todos suavizan, actúan sobre información distinta y en momentos distintos.'] ]},
 fbp:{title:'FBP: una primera imagen de las formas',comparison:'fbp',sections:[
 ['De las vistas al corte','La retroproyección devuelve cada señal hacia las posiciones de donde pudo proceder. Al hacerlo desde muchos ángulos, las estructuras aparecen, pero quedan rodeadas por una especie de nube borrosa. El filtro rampa compensa ese efecto y forma parte de la FBP.'],
 ['Rampa y suavizado no hacen lo mismo','La rampa ayuda a recuperar contornos y también puede hacer más visible el ruido. El suavizado posterior reduce la textura a cambio de detalle. Desactivar la rampa produce retroproyección sin filtrar; no es otra variante de OSEM.'],
 ['Su papel en el recorrido','Aquí FBP ofrece una imagen preliminar para revisar el registro con el TC y una referencia visual para comparar con OSEM. Confirmar el registro no aplica automáticamente atenuación a la FBP. Las correcciones seleccionadas se utilizan después en la reconstrucción iterativa.'] ]},
 registration:{title:'Registro: colocar ambas imágenes en el mismo lugar',comparison:'registration',sections:[
 ['La idea','SPECT describe la distribución de actividad y TC muestra la anatomía. Registrar significa colocar esas dos descripciones del mismo objeto en posiciones compatibles. Los desplazamientos permiten corregir una diferencia de ubicación; no corrigen por sí solos rotaciones o deformaciones.'],
 ['Qué conviene mirar','Comprueba axial, coronal y sagital y recorre distintos cortes. Un contorno que coincide en una imagen puede estar desplazado en otra. La ventana y la mezcla ayudan a reconocer bordes, pero no mueven los tejidos ni mejoran la resolución de los datos.'],
 ['Por qué importa antes de AC','La corrección de atenuación necesita saber qué tejidos atraviesa la señal. Si el mapa está mal colocado, OSEM compensa una pérdida distinta de la real. La ilustración siguiente muestra una desalineación intencional; no representa una prueba de corrección de atenuación.'] ]},
 window:{title:'Ventana: cambiar lo que vemos, no lo que se calculó',comparison:'window',sections:[
 ['La idea','La imagen contiene una amplia variedad de intensidades. La ventana selecciona qué parte de ellas se representa entre oscuro y claro. El nivel mueve ese intervalo; el ancho decide cuántas intensidades caben dentro de él.'],
 ['Qué puede engañarnos','Una ventana estrecha aumenta el contraste aparente y puede saturar las zonas brillantes. Una ventana amplia permite distinguir más intensidades, pero la imagen puede parecer más apagada. Ninguna de las dos recupera detalles ausentes ni modifica la actividad reconstruida.'],
 ['Comparación realizada','Estos tres paneles proceden de la misma matriz de píxeles. Si cambia el tamaño aparente de un foco o desaparece una diferencia, se debe únicamente a su presentación. Al comparar reconstrucciones, mantener una escala compartida evita confundir este efecto con el de una corrección.'] ]},
 timing:{title:'Historial y tiempos: qué trabajo se hizo',comparison:'gaussian',sections:[
 ['La idea','Cada resultado terminado conserva las opciones con las que se calculó y cuánto tardó. El tiempo total incluye preparar los datos, aplicar los modelos necesarios, actualizar la imagen y terminar su presentación. No es una medida de calidad de imagen.'],
 ['Cómo leer los subprocesos','La preparación organiza las proyecciones; la geometría describe cómo se relacionan con los cortes; la atenuación y la dispersión preparan las correcciones. La sensibilidad representa qué zonas puede observar cada grupo de vistas. Las iteraciones refinan la imagen y el filtro final suaviza el volumen obtenido.'],
 ['Por qué algunos cambios son rápidos','Si solo cambia el suavizado final y la reconstrucción base sigue disponible, se reutiliza OSEM. En la comparación siguiente, los tres paneles provienen de un único cálculo y dos filtros posteriores. Además, cuando varios trabajadores calculan a la vez, la suma de sus tiempos puede superar el tiempo que esperaste frente a la pantalla.'] ]},
 data:{title:'Qué información aporta cada archivo',comparison:'iterations',sections:[
 ['SPECT y TC tienen trabajos diferentes','Para reconstruir se necesitan las proyecciones SPECT desde distintos ángulos. Una serie de cortes ya reconstruidos no sustituye esas mediciones. El TC aporta anatomía para la fusión y para preparar el mapa educativo de atenuación; no aporta la captación del radiofármaco.'],
 ['Qué conserva la sesión','El historial mantiene en memoria los resultados terminados. Guardar parámetros o tiempos no guarda las imágenes reconstruidas. Al cambiar de estudio o recargar la página se reinicia ese historial; la exportación DICOM disponible debe leerse según la indicación del panel.'],
 ['Cómo se hicieron estas imágenes de ayuda','Se creó un objeto digital de forma e intensidad conocidas y se simularon señales desde diferentes ángulos, con ruido reproducible. Así podemos comparar un resultado con su referencia sin utilizar imágenes del paciente. Son ejemplos didácticos simplificados, no una reproducción de un equipo comercial.'] ]}
};
