'use strict';
(()=>{
 const help={
 ac:['Corrección de atenuación (AC)','Usa el TC alineado para estimar qué parte de la señal se pierde al atravesar los tejidos. Necesita confirmar el registro. Al desactivarla, OSEM no incluye esa pérdida. El mapa es una aproximación educativa, no una calibración del equipo.'],
 scatter:['Corrección de dispersión','Añade a las proyecciones estimadas una contribución procedente de la ventana energética inferior. Así evita atribuir toda la señal dispersada a la actividad. No es una resta directa de imágenes.'],
 weight:['Peso de dispersión','Multiplica la estimación obtenida de la ventana inferior, además de la relación de anchuras energéticas. Un peso mayor atribuye más cuentas a dispersión. El valor no equivale al porcentaje de fotones dispersados.'],
 psf:['Recuperación de resolución (PSF)','Incluye el desenfoque del colimador y detector dentro de la proyección y retroproyección OSEM. Es un modelo gaussiano experimental; puede aumentar contraste y ruido. No equivale a aplicar nitidez al final.'],
 psfFwhm100:['FWHM a 100 mm','Anchura a mitad de altura de la respuesta gaussiana a 100 mm del detector. Se expresa en milímetros y debe ser mayor o igual a la FWHM intrínseca. El valor inicial de 6 mm no es una calibración Siemens.'],
 psfIntrinsic:['Resolución intrínseca','Componente de la FWHM atribuida al detector. Es el desenfoque propio del detector, además del que introduce el colimador. El valor inicial de 3,5 mm es un parámetro experimental.'],
 distance:['Dependencia de distancia','La PSF se ensancha según la distancia del vóxel al detector usando la órbita del DICOM. Desactivada, usa la anchura indicada a 100 mm para todos los vóxeles. Requiere activar PSF.'],
 axial:['Recuperación axial 3D','Modela también el desenfoque entre cortes. Los cortes quedan acoplados y se reconstruye todo el volumen conjuntamente; tarda más que calcular cortes independientes. Sin esta opción, la PSF actúa solo en el plano transversal.'],
 scatterFilter:['Suavizado de dispersión','Suaviza la ventana inferior antes de incorporarla al modelo de dispersión. El gaussiano actúa en las dos direcciones de cada proyección; reduce fluctuaciones, pero puede borrar variaciones locales. Requiere corrección de dispersión activa.'],
 scatterFwhm:['FWHM de dispersión','Anchura del gaussiano aplicado a las proyecciones de la ventana inferior, en milímetros. No es el filtro final de la imagen OSEM.'],
 filter:['Suavizado final','Aplica un gaussiano 3D después de OSEM. Reduce textura y ruido a costa de detalle. Se usa siempre el volumen sin filtrar; cambiar este ajuste reutiliza el cálculo OSEM cuando está en caché.'],
 fwhm:['FWHM del filtro final','Anchura a mitad de altura del gaussiano, en milímetros. Un valor mayor suaviza más. No modifica el número de iteraciones ni la respuesta del colimador modelada.'],
 fbpStart:['Inicio desde FBP','Utiliza la FBP con rampa como estimación inicial: elimina valores negativos, aplica un pequeño mínimo positivo y normaliza por corte. No usa la FBP suavizada para registro. Desactivado, el inicio es uniforme.'],
 iterations:['Iteraciones','Número de recorridos completos por todos los subconjuntos. Más iteraciones pueden recuperar contraste y aumentar ruido. El primer OSEM del estudio se fija automáticamente en 1 iteración y 1 subconjunto.'],
 subsets:['Subconjuntos','Divide las vistas angulares en grupos intercalados y actualiza la imagen después de cada grupo. Debe dividir exactamente el número de vistas. Una iteración con varios subconjuntos no equivale a una actualización MLEM.'],
 osemScatter95:['Ventana energética inferior','Selecciona las proyecciones que estiman la dispersión. Deben corresponder a las mismas vistas que el fotopico. La estimación se escala por la relación de anchuras energéticas y el peso indicado.'],
 outsideAir95:['Aire fuera del campo TC','Considera como aire las zonas donde falta TC dentro de los cortes cubiertos. Si hay anatomía fuera del campo, esta hipótesis introduce error. No rellena los cortes sin ninguna cobertura TC ni corrige el truncamiento.'],
 runOsem95:['Nueva reconstrucción','Calcula todos los cortes elegibles con las opciones seleccionadas. Guarda un nuevo resultado y su duración; conserva los anteriores. El primer resultado se calcula con 1×1.'],
 cancelOsem95:['Detener','Cancela el cálculo en curso, incluido el filtro final pendiente. No añade un resultado incompleto al historial; conserva las reconstrucciones terminadas.'],
 saveHistory95:['Guardar historial','Descarga un JSON con los parámetros, tiempos y cobertura de cada reconstrucción de esta sesión. No incluye los píxeles ni permite recuperar los volúmenes al recargar.'],
 saveConfig:['Guardar configuración','Descarga las opciones actuales. Guardar opciones no calcula ni exporta una imagen DICOM.'],
 historyTop95:['Reconstrucción superior','Selecciona un resultado terminado para las tres vistas de arriba. La fila conserva los parámetros con que se calculó, aunque cambies las opciones del panel.'],
 historyBottom95:['Reconstrucción inferior','Selecciona un resultado terminado para las tres vistas de abajo. Permite compararlo con cualquier otro del historial.'],
 historyAxial95:['Corte axial','Desplaza el mismo corte axial en ambas filas. No vuelve a reconstruir.'],historyCoronal95:['Corte coronal','Desplaza el mismo plano coronal en ambas filas. No vuelve a reconstruir.'],historySagittal95:['Corte sagital','Desplaza el mismo plano sagital en ambas filas. No vuelve a reconstruir.'],
 osemWindow95:['Ventana de comparación','Cambia el brillo mostrado. Las dos reconstrucciones OSEM seleccionadas comparten escala; FBP conserva una escala propia. No modifica los valores reconstruidos.'],
 energy95:['Ventana de fotopico','Elige las proyecciones energéticas usadas para FBP y OSEM. Cambiarla requiere generar de nuevo la FBP.'],
 ramp95:['Filtro rampa','Filtro de frecuencias que forma parte de la retroproyección filtrada (FBP). Puede acentuar el ruido. Sin él se obtiene retroproyección sin filtrar, no FBP.'],
 smooth95:['Suavizado para registro','Suaviza la imagen preliminar en tres dimensiones para facilitar su alineación con TC. Se conserva la FBP original y no se modifica el mapa μ.'],
 smoothWidth95:['FWHM para registro','Anchura del gaussiano de la vista preliminar, en milímetros. Es independiente del filtro final OSEM.'],
 confirm95:['Confirmar registro','Acepta los desplazamientos elegidos y prepara el mapa μ educativo. No aplica automáticamente AC a la FBP. Revisa antes la alineación en los tres planos.'],
 rx95:['Desplazamiento X','Traslada el TC en milímetros respecto del SPECT en el eje X. Invalida el mapa μ anterior.'],ry95:['Desplazamiento Y','Traslada el TC en milímetros respecto del SPECT en el eje Y. Invalida el mapa μ anterior.'],rz95:['Desplazamiento Z','Traslada el TC en milímetros respecto del SPECT en el eje Z. Invalida el mapa μ anterior.'],
 ctWindow95:['Preajuste TC','Fija nivel y ancho de ventana para hueso, tejido blando o contorno externo. Solo modifica la visualización.'],
 blend95:['Mezcla de fusión','0 % muestra TC; al aumentar se superpone más señal SPECT. Cambiar la mezcla no cambia el registro ni activa AC.'],
 spectLevel95:['Nivel SPECT','Centro de la ventana, en porcentaje de la referencia global de intensidad. Ayuda a resaltar bordes sin cambiar los píxeles reconstruidos.'],spectWidth95:['Ancho SPECT','Rango de intensidades mostrado. Un ancho menor aumenta el contraste y puede saturar la imagen.'],ctLevel95:['Nivel TC','Centro de la ventana en unidades Hounsfield (HU). Solo afecta a la imagen mostrada.'],ctWidth95:['Ancho TC','Rango HU mostrado de negro a blanco. Estrecharlo aumenta el contraste; no aumenta la resolución espacial.']
 };
 Object.assign(help,{
 fbp95:['Generar FBP','Calcula la reconstrucción preliminar de todas las filas del fotopico con el filtro rampa seleccionado. Sirve para revisar el registro y comparar posteriormente con OSEM.'],cancel95:['Detener FBP','Detiene el cálculo preliminar y descarta un volumen incompleto.'],
 livePlane95:['Plano de registro','Cambia entre axial, coronal y sagital para revisar la alineación TC/SPECT.'],liveSlice95:['Corte de registro','Desplaza el plano mostrado sin recalcular FBP. Revisa varios cortes antes de confirmar el registro.'],resetWindows95:['Restablecer ventanas','Restaura el nivel y ancho de visualización de SPECT y TC. No cambia los desplazamientos de registro.'],
 spectFile:['Proyecciones SPECT','Carga directamente un DICOM NM con proyecciones tomográficas originales. No se acepta una reconstrucción como entrada de OSEM.'],spectFolder:['Carpeta de estudio','Examina una carpeta completa. Las adquisiciones SPECT aparecen en su lista y las series TC encontradas aparecen también en la lista TC.'],spectSeries:['Adquisición SPECT','Elige cuál archivo de proyecciones tomográficas se cargará. La compatibilidad completa se comprueba al seleccionarlo.'],ctFiles:['Archivos TC','Examina los cortes TC seleccionados y los agrupa por serie. Después debes elegir una serie.'],ctFolder:['Carpeta de estudio','Examina una carpeta completa. Las series TC aparecen en su lista y las adquisiciones SPECT encontradas aparecen también en la lista SPECT.'],ctSeries:['Serie TC','Elige la serie que se usará para fusión y mapa μ. No se selecciona automáticamente la primera serie.'],
 new:['Nuevo estudio','Reinicia entradas, resultados e historial de esta sesión para cargar otro estudio. Guarda antes el registro si lo necesitas.']
 });
 for(const side of ['Top','Bottom']){help['history'+side+'Plane95']=['Plano del panel','Selecciona axial, coronal o sagital solo para este panel. Para comparar la misma zona, elige también el mismo plano en el otro.'];help['history'+side+'Slice95']=['Corte del panel','Recorre los cortes del plano seleccionado, sin reconstruir. El otro panel conserva su corte.'];}
 help.historyTop95=['Reconstrucción izquierda','Selecciona un resultado del historial para el panel izquierdo. Conserva sus parámetros originales.'];help.historyBottom95=['Reconstrucción derecha','Selecciona el resultado que quieres comparar a la derecha. Los nuevos resultados aparecen aquí.'];
 for(const base of ['spectLevel','spectWidth','ctLevel','ctWidth'])help[base+'Number95']=help[base+'95'];
 const topicFor=id=>{
  if(['ac','outsideAir95'].includes(id))return 'ac';
  if(['scatter','weight','scatterFilter','scatterFwhm','osemScatter95'].includes(id))return 'scatter';
  if(['psf','psfFwhm100','psfIntrinsic','distance'].includes(id))return 'psf';
  if(id==='axial')return 'axial';if(id==='iterations')return 'iterations';if(id==='subsets')return 'subsets';if(id==='fbpStart')return 'initialization';
  if(['filter','fwhm','smooth95','smoothWidth95'].includes(id))return 'gaussian';
  if(['energy95','ramp95','fbp95','cancel95'].includes(id))return 'fbp';
  if(['confirm95','rx95','ry95','rz95','livePlane95','liveSlice95'].includes(id))return 'registration';
  if(['spectFile','spectFolder','spectSeries','ctFiles','ctFolder','ctSeries','new'].includes(id))return 'data';
  if(id.includes('Level')||id.includes('Width')||['ctWindow95','blend95','resetWindows95','plane','slice','window','swap','osemWindow95'].includes(id)||id.startsWith('historyA')||id.startsWith('historyC')||id.startsWith('historyS'))return 'window';
  return 'timing';
 };
 const lessonDialog=document.createElement('dialog');lessonDialog.id='lessonDialog95';lessonDialog.setAttribute('aria-labelledby','lessonTitle95');
 lessonDialog.innerHTML='<header class="titlebar"><span id="lessonTitle95">Guía docente</span><button type="button" id="lessonX95" aria-label="Cerrar explicación">×</button></header><div class="lessonNav95"><label>Tema <select id="lessonTopic95"></select></label><span>Ayuda para estudiantes · no modifica la configuración</span></div><div id="lessonBody95" tabindex="0"></div><footer><button type="button" id="lessonClose95">Cerrar</button></footer>';
 document.body.append(lessonDialog);const topicSelect=lessonDialog.querySelector('#lessonTopic95'),body=lessonDialog.querySelector('#lessonBody95');let opener=null;
 for(const [id,lesson] of Object.entries(SPECT95_LESSONS))topicSelect.add(new Option(lesson.title,id));
 function paragraph(text,parent=body){const p=document.createElement('p');p.textContent=text;parent.append(p);return p;}
 function heading(text,parent=body){const h=document.createElement('h3');h.textContent=text;parent.append(h);}
 function openLesson(id,topic=topicFor(id)){
  hide();const lesson=SPECT95_LESSONS[topic]||SPECT95_LESSONS.overview;topicSelect.value=topic;document.getElementById('lessonTitle95').textContent='Guía docente · '+(help[id]?.[0]||lesson.title);body.replaceChildren();
  if(id&&help[id]){heading(help[id][0]);paragraph(help[id][1]);const control=document.getElementById(id);if(control){const value=control.type==='checkbox'?(control.checked?'Marcada':'Desmarcada'):control.type==='file'?'Archivo local':control.tagName==='SELECT'?control.selectedOptions[0]?.textContent:control.value; if(value)paragraph('Estado actual del control: '+value+(control.disabled?' (inactivo por dependencia).':'.'));}}
  const h=document.createElement('h2');h.textContent=lesson.title;body.append(h);
  for(const [title,text]of lesson.sections){heading(title);paragraph(text);}
  const example=SPECT95_PHANTOMS[lesson.comparison];
  if(example){const section=document.createElement('section');section.className='lessonComparison95';heading('Comparación realizada con fantoma',section);paragraph('Fantoma digital sintético. No son imágenes del paciente ni resultados Siemens. Los ejemplos están precalculados y no modifican tu estudio.',section);const grid=document.createElement('div');grid.className='phantomGrid95';for(const item of example.images){const figure=document.createElement('figure'),img=document.createElement('img'),caption=document.createElement('figcaption');img.src=item.src;img.alt=item.label+' — '+lesson.title;img.width=256;img.height=256;caption.textContent=item.label;figure.append(img,caption);grid.append(figure);}section.append(grid);paragraph(example.note,section);paragraph('En los ejemplos SPECT se usa un modelo paralelo simplificado de 64 vistas y un fantoma de 64 × 64 píxeles, con ruido simulado reproducible. Se comparte la escala salvo cuando se indica otra cosa. El ejemplo axial y la fusión son demostraciones específicas descritas en sus leyendas.',section);body.append(section);}
  const extremeTopics=topic==='gaussian'?['gaussian','fbp']:[topic];
  const extraKeys=extremeTopics.flatMap(key=>SPECT95_PHANTOMS._extremes?.[key]||[]);
  if(extraKeys.length){heading('¿Qué pasa en los extremos del control?');paragraph('Estos ejemplos usan los límites que permite el simulador. Son experimentos con un fantoma de 4 mm por píxel, no valores recomendados. En cada fila solo cambia la opción indicada. Las imágenes ya están calculadas: abrirlas no inicia una reconstrucción.');}
  for(const key of extraKeys){const example=SPECT95_PHANTOMS[key],section=document.createElement('section');section.className='lessonComparison95 extremeComparison95';section.dataset.example=key;heading(example.title,section);const grid=document.createElement('div');grid.className='phantomGrid95';for(const item of example.images){const figure=document.createElement('figure'),img=document.createElement('img'),caption=document.createElement('figcaption');img.src=item.src;img.alt=item.label+' — '+example.title;img.width=256;img.height=256;caption.textContent=item.label;figure.append(img,caption);grid.append(figure);}section.append(grid);paragraph(example.note,section);body.append(section);}
  heading('Lecturas complementarias');paragraph('Estas referencias amplían los principios de reconstrucción; no certifican los parámetros ni los resultados de este simulador.');
  for(const [title,url] of [['IAEA · Quantitative Nuclear Medicine Imaging: Concepts, Requirements and Methods','https://www-pub.iaea.org/MTCD/Publications/PDF/Pub1605_web.pdf'],['Estudio sobre SPECT/CT con OSEM 3D, atenuación y dispersión (Journal of Nuclear Medicine)','https://jnm.snmjournals.org/content/51/6/921']]){const p=document.createElement('p'),a=document.createElement('a');a.textContent=title;a.href=url;a.target='_blank';a.rel='noopener noreferrer';p.append(a);body.append(p);}
  if(!lessonDialog.open){opener=document.activeElement;lessonDialog.showModal();}body.scrollTop=0;body.focus();
 }
 topicSelect.onchange=()=>openLesson(null,topicSelect.value);for(const id of ['lessonX95','lessonClose95'])document.getElementById(id).onclick=()=>lessonDialog.close();lessonDialog.addEventListener('close',()=>{if(opener?.isConnected)opener.focus();});

 const popup=document.createElement('div');popup.id='helpPopup95';popup.setAttribute('role','tooltip');popup.setAttribute('aria-label','Ayuda de la opción');popup.hidden=true;document.body.append(popup);let current=null,hideTimer;
 for(const id of Object.keys(help)){const control=document.getElementById(id);if(!control)continue;control.dataset.help95=id;const label=control.closest('label');if(label){label.dataset.help95=id;for(const node of [...label.childNodes]){if(node.nodeType!==Node.TEXT_NODE||!node.textContent.trim())continue;const name=document.createElement('span');name.className='helpName95';name.textContent=node.textContent;name.dataset.help95=id;name.tabIndex=0;name.setAttribute('role','button');name.setAttribute('aria-haspopup','dialog');name.setAttribute('aria-label','Explicación: '+help[id][0]);const activate=event=>{event.preventDefault();event.stopPropagation();openLesson(id);opener=name;};name.addEventListener('click',activate);name.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' ')activate(event);});node.replaceWith(name);}}}
 function hide(){clearTimeout(hideTimer);if(current){current.removeAttribute('aria-describedby');current=null;}popup.hidden=true;}
 function later(){clearTimeout(hideTimer);hideTimer=setTimeout(hide,220);}
 function show(target){if(popup.contains(target)){clearTimeout(hideTimer);return;}const anchor=target?.closest?.('[data-help95]');if(!anchor){later();return;}clearTimeout(hideTimer);if(anchor===current)return;hide();current=anchor;anchor.setAttribute('aria-describedby',popup.id);const [title,description]=help[anchor.dataset.help95],head=document.createElement('strong'),text=document.createElement('p'),link=document.createElement('p');head.textContent=title;text.textContent=description;link.className='helpHint95';link.textContent=anchor.classList.contains('helpName95')||anchor.closest('label')?'Haz clic en el nombre para saber más':'Haz clic con el botón derecho para saber más';popup.replaceChildren(head,text,link);popup.hidden=false;const r=anchor.getBoundingClientRect(),w=popup.offsetWidth,h=popup.offsetHeight;popup.style.left=Math.max(8,Math.min(r.left,innerWidth-w-8))+'px';popup.style.top=Math.max(8,r.bottom+h+8<innerHeight?r.bottom+6:r.top-h-6)+'px';}
 document.addEventListener('mouseover',event=>show(event.target));document.addEventListener('focusin',event=>show(event.target));
 document.addEventListener('focusout',event=>{if(!popup.contains(event.relatedTarget))later();});
 document.addEventListener('contextmenu',event=>{const anchor=event.target.closest?.('[data-help95]');if(!anchor)return;event.preventDefault();event.stopPropagation();const id=anchor.dataset.help95;openLesson(id);opener=document.getElementById(id)||anchor;},true);
 document.addEventListener('keydown',event=>{if(event.key==='Escape')hide();});
 document.addEventListener('scroll',hide,true);window.addEventListener('resize',hide);document.addEventListener('mouseout',event=>{if(!event.relatedTarget)later();});
})();
